// src/routes/privacy-policy.svelte
<svelte:head>
  <title>Privacy Policy for Random Name Generators</title>
  <meta name="description" content="Our Privacy Policy - Learn how we collect and use information and usage data on our site.">
</svelte:head>

<h2>Privacy Policy of Random Name Generators</h2>
<p class="bold">Updated February 24, 2020</p>
<p>Your privacy is important! Here is the information we collect and use when you visit random-name-generators.com. We will not use or share your information with anyone except as described in this privacy policy.</p>
<p>By using our name generators, you agree to the collection and use of information as stated in this privacy policy.</p>
<h3>Log Data</h3>
<p>When you visit our website, we collect information that your browser sends to us called Log Data. Log Data may include information such as your computer's Internet Protocol (“IP”) address, browser version, the time and date of your visit, name generators you visit, the time spent on those pages, and other usage stats and information.</p>
<h3>Cookies & Web Beacons</h3>
<p>Random Name Generators uses Google Analytics as its Data Processor.</p>
<p>Cookies are files with a small amount of data that is commonly used as an anonymous unique identifier. These are sent to your browser from the website that you visit and are stored on your computer's hard drive.</p>
<p>Our website uses these “cookies” to collect information and to improve your experience. You can choose to disable or manage your cookie settings in your browser settings. If you choose to refuse cookies, your website experience (such as load speed) may be affected.</p>
<p>Third party vendors, including Google, may use technology such as cookies and web beacons when they serve you advertisements. Advertisers will be sent information including your IP address, your ISP, the browser you used to visit our site, and in some cases, whether you have Flash installed.</p>
<p>Advertisers use this technology to serve you personalized ads based on prior visits to our website or other websites. For example, it can sometimes be used for geotargeting purposes (like showing New York-specific ads to someone in New York) or showing certain ads based on specific sites visited (such as showing cooking ads to someone who frequents cooking sites).</p>
<p>You may opt out of personalized advertising by visiting <a href="https://adssettings.google.com/authenticated">Ad Settings</a>.</p>
<h3>Links to Other Sites</h3>
<p>Random Name Generators contains advertisements that link to other sites. If you click on a third-party link, you will be directed to that site. These external sites are not operated by us. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.</p>
<h3>Children's Privacy</h3>
<p>Our name generators do not address anyone under the age of 13. We do not knowingly collect personal identifiable information from children under 13. In the case we discover that a child under 13 has provided us with personal information, we will immediately delete this from our servers.</p>
<p>If you are a parent or guardian and you are aware that your child has provided us with personal information, please contact us so that we will be able to take necessary action.</p>
<h3>Changes to This Privacy Policy</h3>
<p>This privacy policy was last updated on February 24, 2020. We may update our privacy policy from time to time, so review this page periodically for changes. New policies updated to this privacy policy are effective immediately after they are posted on this page.</p>
<h3>Contact Us</h3>
<p>If you have any questions or suggestions about our privacy policy, contact us at thecharactercomma@gmail.com.</p>

<style>
  h2, h3 {
    color: var(--text-green);
  }
  h3 {
    font-size: 1.5rem;
  }
  p {
    color: var(--text-white);
    margin-bottom: 1rem;
  }
  a {
    text-decoration: none;
    color: var(--text-green);
  }
  a:visited {
    color: #2fadb1;
  }
  .bold {
    font-weight: bold;
  }
</style>

// pages/privacy-policy.vue
<template>
  <div class="text-white">
    <h1 class="text-3xl text-pallet-text">Privacy Policy of Random Name Generators</h1>
    <h2 class="font-bold pb-4">Updated February 24, 2020</h2>
    <p>Your privacy is important! Here is the information we collect and use when you visit random-name-generators.com. We will not use or share your information with anyone except as described in this privacy policy.</p>
    <p>By using our name generators, you agree to the collection and use of information as stated in this privacy policy.</p>
    <h2 class="text-2xl text-pallet-text">Log Data</h2>
    <p>When you visit our website, we collect information that your browser sends to us called Log Data. Log Data may include information such as your computer's Internet Protocol (“IP”) address, browser version, the time and date of your visit, name generators you visit, the time spent on those pages, and other usage stats and information.</p>
    <h2 class="text-2xl text-pallet-text">Cookies & Web Beacons</h2>
    <p>Random Name Generators uses Google Analytics as its Data Processor.</p>
    <p>Cookies are files with a small amount of data that is commonly used as an anonymous unique identifier. These are sent to your browser from the website that you visit and are stored on your computer's hard drive.</p>
    <p>Our website uses these “cookies” to collect information and to improve your experience. You can choose to disable or manage your cookie settings in your browser settings. If you choose to refuse cookies, your website experience (such as load speed) may be affected.</p>
    <p>Third party vendors, including Google, may use technology such as cookies and web beacons when they serve you advertisements. Advertisers will be sent information including your IP address, your ISP, the browser you used to visit our site, and in some cases, whether you have Flash installed.</p>
    <p>Advertisers use this technology to serve you personalized ads based on prior visits to our website or other websites. For example, it can sometimes be used for geotargeting purposes (like showing New York-specific ads to someone in New York) or showing certain ads based on specific sites visited (such as showing cooking ads to someone who frequents cooking sites).</p>
    <p>You may opt out of personalized advertising by visiting <a href="https://adssettings.google.com/authenticated" target="_blank">Ad Settings</a>.</p>
    <h2 class="text-2xl text-pallet-text">Links to Other Sites</h2>
    <p>Random Name Generators contains advertisements that link to other sites. If you click on a third-party link, you will be directed to that site. These external sites are not operated by us. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.</p>
    <h2 class="text-2xl text-pallet-text">Children's Privacy</h2>
    <p>Our name generators do not address anyone under the age of 13. We do not knowingly collect personal identifiable information from children under 13. In the case we discover that a child under 13 has provided us with personal information, we will immediately delete this from our servers.</p>
    <p>If you are a parent or guardian and you are aware that your child has provided us with personal information, please contact us so that we will be able to take necessary action.</p>
    <h2 class="text-2xl text-pallet-text">Changes to This Privacy Policy</h2>
    <p>This privacy policy was last updated on February 24, 2020. We may update our privacy policy from time to time, so review this page periodically for changes. New policies updated to this privacy policy are effective immediately after they are posted on this page.</p>
    <h2 class="text-2xl text-pallet-text">Contact Us</h2>
    <p>If you have any questions or suggestions about our privacy policy, contact us at thecharactercomma@gmail.com.</p>
  </div>
</template>

<script>
export default {
  head () {
    return {
      title: 'Privacy Policy for Random Name Generators',
      meta: [
        { hid: 'description', name: 'description', content: 'Our Privacy Policy - Learn how we collect and use information and usage data on our site.' }
      ]
    }
  }
}
</script>

<style scoped>
  p {
    padding-bottom: 1em;
  }
</style>

<style scoped>
  a:link {
    color: #00cda2;
  }
  a:visited {
    color: #2fadb1;
  }
</style>
