// pages/g/boy.vue
<template>
  <div>
    <Generator
      title="Boy Name Generator"
      :names="names"
      :image="image"
    />
    <button
      @click="getNames"
      class="w-full px-4 py-3 mt-4 text-lg antialiased font-bold rounded-lg shadow outline-none text-pallet-navbar bg-pallet-text border-pallet-navbar sm:w-48"
    >Get More Names</button>
    <hr class="mt-6">
    <!-- <img
      class="w-full mt-6 rounded"
      src="https://via.placeholder.com/500x70"
      alt=""
    > -->
    <ExploreMore title="Explore More Generators" />
    <div class="mt-8">
      <h2 class="text-2xl text-center rounded shadow-lg md:text-3xl bg-pallet-sidebar md:pl-4 md:text-left">About This Generator</h2>
      <div class="text-gray-300 lg:flex">
        <div class="flex-1 p-4 m-2 mt-4 ml-0 mr-0 rounded shadow-xl lg:mr-2 bg-pallet-background">
          <h3 class="pb-2 text-2xl">Random Boy Name Generator</h3>
          <p class="pb-2">In need of a random male name? You’ve come to the right place! Find male name ideas or use it as a character name generator for the boys and men in your novel — you decide.</p>
          <p class="pb-2">This boy name generator includes over 900 male names from different time periods and cultural origins to offer a huge variety of options. Alternate spellings are also included so you can get creative and unique.</p>
          <p>Each time you click, the generator will create a list of 12 random boy names. If you don’t like your options, simply click again and you’ll get 12 more to choose from.</p>
        </div>
        <div class="flex-1 p-4 m-2 mt-4 ml-0 mr-0 rounded shadow-xl bg-pallet-background lg:ml-2">
          <h3 class="pb-2 text-2xl">Generators for Male Names & More</h3>
          <p class="pb-2">We’ve taken the time to gather and curate thousands of names and build them into fun and easy-to-use <router-link to="/">name generators</router-link>.</p>
          <p class="pb-2">In addition to boy names, we also have a <router-link to="/g/girl">girl name generator</router-link>, a <router-link to="/g/unisex">unisex name generator</router-link>, and many more! You’re sure to find a name that fits your needs.</p>
          <p>We update each generator as we find new names so we can continue to offer as many choices as possible. Explore all our generators and have fun!</p>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import ExploreMore from '~/components/ExploreMore.vue'
import Generator from '~/components/Generator.vue'
import boyNames from '~/static/names/boy.json'
import boyNameImage from '~/static/images/boy-male-name-generator.png'

export default {
  components: {
    Generator,
    ExploreMore
  },
  data: function () {
    return {
      names: [],
      image: boyNameImage
    }
  },
  methods: {
    getNames () {
      const tempArr = []
      for (let i = 0; i < 12; i++) {
        const randomIndex = Math.floor(Math.random() * boyNames.names.length)
        if (!tempArr.includes(boyNames.names[randomIndex])) {
          tempArr.push(boyNames.names[randomIndex])
          this.names = tempArr
        } else {
          i--
        }
      }
    }
  },
  mounted: function () {
    this.getNames()
  },
  head () {
    return {
      title: 'Boy Name Generator - Get Random Male Names!',
      meta: [
        { hid: 'description', name: 'description', content: 'Find the perfect boy name with this name generator, male edition! Discover hundreds of random male names for characters, babies and more.' }
      ]
    }
  }
}
</script>

<style scoped>
  a:link {
    color: #00cda2;
  }
  a:visited {
    color: #2fadb1;
  }
</style>

// src/routes/g/boy.svelte
<script>
  import { onMount } from "svelte";
  import { generatedNames } from '/src/stores.js';
  import NameDisplay from '../../components/name-display.svelte';
  import SectionTitle from '../../components/section-title.svelte';
  import Button from '../../components/button.svelte';
  import ExploreMore from '../../components/explore-more.svelte';
  import Textbox from '../../components/textbox.svelte';

  async function getRandomNames() {
    const res = await fetch('/api/get/random/12/category/1');
    const names = await res.json();
    const namesArr = names.rows;
    generatedNames.set(namesArr)
  }
  onMount(async () => {
    getRandomNames()
  })
</script>

<svelte:head>
  <title>Boy Name Generator - Get Random Male Names!</title>
  <meta name="description" content="Find the perfect boy name with this name generator, male edition! Discover hundreds of random male names for characters, babies and more.">
</svelte:head>

<div>
  <SectionTitle mb="1rem"><h1>Boy Name Generator</h1></SectionTitle>
  <NameDisplay mb="1rem">
    <img src="/boy-male-name-generator.png" alt="Random Boy Names" title="Random Boy Names">
  </NameDisplay>
  <Button on:click="{getRandomNames}">Get More Names</Button>
  <hr>
  <SectionTitle>
    <h2>Explore More Generators</h2>
  </SectionTitle>
  <ExploreMore mt="1rem" mb="2rem"></ExploreMore>
  <SectionTitle>
    <h2>About This Generator</h2>
  </SectionTitle>
  <Textbox mt="1rem" mb="1rem">
    <div>
      <h3>Random Boy Name Generator</h3>
      <p class="small">In need of a random male name? You’ve come to the right place! Find male name ideas or use it as a character name generator for the boys and men in your novel — you decide.</p>
      <p class="small">This boy name generator includes over 900 male names from different time periods and cultural origins to offer a huge variety of options. Alternate spellings are also included so you can get creative and unique.</p>
      <p class="small">Each time you click, the generator will create a list of 12 random boy names. If you don’t like your options, simply click again and you’ll get 12 more to choose from.</p>
    </div>
    <div>
      <h3>Generators for Male Names & More</h3>
      <p class="small">We’ve taken the time to gather and curate thousands of names and build them into fun and easy-to-use <a href="/">name generators</a>.</p>
      <p class="small">In addition to boy names, we also have a <a href="/g/girl">girl name generator</a>, a <a href="/g/unisex">unisex name generator</a>, and many more! You’re sure to find a name that fits your needs.</p>
      <p class="small">We update each generator as we find new names so we can continue to offer as many choices as possible. Explore all our generators and have fun!</p>
    </div>
  </Textbox>  
</div>
